### ISSUE TITLE
Composer gives wrong dependencies package name

### ISSUE THREAD

**Issue by haithamalnaeb** [andrewdalpino/Rubix-engine#199]
I just tried to fresh install latest release (1.3) using PHP 8 on win 11
I got this error in composer:
rubix/ml 1.3.0 requires scienide/okbloomer ^**1.0@beta** -> found scienide/okbloomer[**1.0.0-beta1**] but it does not match your minimum-stability.

adding -W didn't help to fix the issue, so I installed release 1.2.3 and all went smoothly.

Another note, when I already had packages before, I couldn't install 1.3 because of this error:
rubix/ml 1.3.0 requires psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

1.2.3 works fine for me, but I thought better to report this issue

Great work overall

**Comment by andrewdalpino** [comment]
Ok thanks @haithamalnaeb, I'll take a look ASAP

**Comment by andrewdalpino** [comment]
Hey @haithamalnaeb let me know if the latest release 1.3.1 solves the problem. The Ok Bloomer package that powers the new Deduplicator extractor was still in beta but I released it as stable now.

https://github.com/RubixML/ML/commit/618a5b2c0d9f2a932814c72fe84e39a7719a2438

**Comment by haithamalnaeb** [comment]
@andrewdalpino yes indeed
problem solved with 1.3.1. thank you

the second problem "require psr/log ^1.1" still exists if I have other packages already installed with psr/log 3.0, but this can be fixed by adding -W, or simply by deleting vendor and composer.lock

**Comment by andrewdalpino** [comment]
I thought version 1.1 of `psr/log` was the latest up until now

https://github.com/php-fig/log/releases

**Comment by haithamalnaeb** [comment]
I had filp/whoops package installed earlier, which install  psr/log 1.0 or 2.0 or 3.0, 
https://github.com/filp/whoops/blob/master/composer.json

so it installed 3.0
it is not declared as release but it is still available in composer:
https://github.com/php-fig/log/tags

**Comment by allanmcarvalho** [comment]
Isn't impossible to use this package with Laravel 9 and 10 because laravel requires monolog and monolog requires psr/log 2|3....
Can we easily  upgrate the psr/log to 2 or 3?
