### ISSUE TITLE
Recommendation: How do I implement it using RubixML ?

### ISSUE THREAD

**Issue by ghost** [andrewdalpino/Rubix-engine#215]
Hello, I'm looking to implement a recommendation engine using RubixML, but I see no documentation regarding this.

The idea is 3 files:
1. containing user id and it's dimensions
2. containing item id and it's dimentions
3. containing interaction that a user has with an item (user_id, item_id, score)

Any idea / example ?

Thanks

**Comment by ghost** [comment]
@andrewdalpino Any idea / example ? Thank you very much.

**Comment by andrewdalpino** [comment]
Right, we try to provide examples of common applications of Machine Learning but we cannot give examples for every problem. Recommendation systems are not unique to Rubix ML or PHP but rather a use case for Machine Learning in general. I would recommend searching for papers, software repos, and blog articles on how to implement a recommendation system using Machine Learning. Then you can reference the Rubix ML docs for how to apply those methods in PHP with the library. A google place to start might be the "Netflix prize."

https://en.wikipedia.org/wiki/Netflix_Prize

Another method that I see employed alot is to cluster your users and then to recommend content that users from the same cohort tend to interact with but that has not been interacted with by a user in question so far. The Color Clusterer project might be helpful in getting you started.

https://github.com/RubixML/Colors
