### ISSUE TITLE
Does the target column always have to be at the end of a data table?

### ISSUE THREAD

**Issue by ghost** [andrewdalpino/Rubix-engine#224]
Hello, do the target column have to always be at the end of line ? (last column for CSV ?)
Is it possible to specify which column is the target ?
Thanks

**Comment by ghost** [comment]
@andrewdalpino any idea ? Thanks.

**Comment by andrewdalpino** [comment]
Hey, @zenati thanks for the question! By convention, in a labeled dataset, the last column of the data table is reserved for the label. If you would like to use the values from another column as the label you can rearrange the column order in-flight using Column Picker.

https://docs.rubixml.com/1.0/extractors/column-picker.html

An example can be found in the Housing example project.

https://github.com/RubixML/Housing
