### ISSUE TITLE
How to reset values after a day

### ISSUE THREAD

**Issue by DerekVictor1** [andrewdalpino/Rubix-engine#236]
I'm working on something where a user searches with he/she id and it stores  in the database after 5 searches the user cannot search again until the next day it resets to 0 and continues again, but I keep getting error and when it resets it resets for the whole day even one's that isn't the id of the user.

**Comment by andrewdalpino** [comment]
Hey @DerekVictor1 it looks like this question might have been posted to the wrong repo. I am closing it to prevent confusion but feel free to reply back if I am mistaken. Thank you!

**Comment by DerekVictor1** [comment]
> 

Bro sorry but I'm in need of help in that question that's why I posted it 
I'm sorry I didn't know it shouldn't be here but would love it if possible someone can look into it.

**Comment by DerekVictor1** [comment]
Hey Andrew please can you help me with the solution to the problem I am
having difficulty in that problem I keep getting wrong values with
everything I have tried do you have any alternative to answering it
