### ISSUE TITLE
Persistent model requires exact dimension to predict

### ISSUE THREAD

**Issue by mataluis2k** [andrewdalpino/Rubix-engine#237]
Thank you for putting this great project together, I have been using it since it was 0.3.1. Trying to use version 2.0, but I'm stumped on an issue I can't seem to get past. 

Basically, I have a persistent model 

 $estimator = new PersistentModel(
                new LogisticRegression(64, new Adam(0.01)),
                new Filesystem($modelName, true)
            );

$estimator->train($training);
$estimator->save();

This all works perfectly, and if I validate the model in the same PHP session it works!. But if I try to load the persistent model in a different PHP session then this happens 
 $dataset = Labeled::fromIterator(new CSV($filename,true))
        ->apply(new NumericStringConverter())
        ->apply(new OneHotEncoder())
        ->apply(new ZScaleStandardizer());

 $estimator2 = PersistentModel::load(new Filesystem($modelName)); 

$predictions = $estimator->predict($dataset);

78
sample1.rbx

   Rubix\ML\Exceptions\IncorrectDatasetDimensionality 

  Dataset must contain samples with exactly 2107 dimensions, 81 given.

  at vendor/rubix/ml/src/Specifications/DatasetHasDimensionality.php:64
     60▕      */
     61▕     public function check() : void
     62▕     {
     63▕         if ($this->dataset->numFeatures() !== $this->dimensions) {
  ➜  64▕             throw new IncorrectDatasetDimensionality($this->dataset, $this->dimensions);
     65▕         }
     66▕     }
     67▕ }
     68▕ 

The model was trained with 2000 records, but for prediction, I'm only passing 78 records, which triggers the error message. In previous version I was able to predict by only passing one record. Is there something different I need to do with version 2.0 ? Or is it a bug?

My configs...

composer 
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "rubix/ml": "^2.0"

PHP 8.0.14 (cli) (built: Dec 21 2021 15:10:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.14, Copyright (c) Zend Technologies

**Comment by andrewdalpino** [comment]
The problem seems to be that you are not using the Transformer fittings from the training session when performing inference. Otherwise, OneHotEncoder would have created the extra columns needed.

You can either save the Transformer fittings and then load them into the inference script, or you can save them in a Pipeline with the model all at the same time.

See

https://docs.rubixml.com/2.0/model-persistence.html#persisting-transformers

https://docs.rubixml.com/2.0/preprocessing.html#transformer-pipelines

**Comment by mataluis2k** [comment]
Andrew!, 

    That did it!. Well done. Works like a charm. I will spell it out here for those who might have the same issue going forward. And please let me know if there is a better way to do it. 

To train the model and save it with the transformer fittings I changed the trainer initialization to this:
`
// Load your labeled dataset to train the model 
 $dataset = Labeled::fromIterator(new CSV($filename, true));

// Instantiate hot encoder with training algo

 $estimator = new PersistentModel(new Pipeline([
                new NumericStringConverter(),
                new OneHotEncoder(),
                new ZScaleStandardizer(),
            ],  new LogisticRegression(64, new Adam(0.01))),new Filesystem($modelName, true));

// Then easy as 

$handle = $estimator->train($training);
$estimator->save();
`
In another process you could do the following to predict values, in this case, I'm loading an unlabeled dataset:
`
    $dataset = unlabeled::fromIterator(new CSV($filename,true));

// Load your trained model ...
  $estimator = PersistentModel::load(new Filesystem($model)); 

// Pass your unlabeled data to predict  ...
 $predictions = $estimator->predict($dataset);

// User $predictions as needed. 
`
:-)

**Comment by mataluis2k** [comment]
Thanks!, for the fast response!.
