### ISSUE TITLE
Warning: Ambiguous class resolution, `Rubix\ML\Kernels\Distance\Gower`

### ISSUE THREAD

**Issue by andrey-helldar** [andrewdalpino/Rubix-engine#260]
I'm using the `BM25Transformer` transformer contained in the [`rubixml/extras`](https://github.com/RubixML/Extras) repository, but after updating RubixML to version 2.2, a warning occurs when installing dependencies:

> Warning: Ambiguous class resolution, "Rubix\ML\Kernels\Distance\Gower" was found in both "D:/domains/dragon-code/apps/webhooks/vendor/rubix/extras/src\Kernels\Distance\Gower.php" and "D:/domains/dragon-code/apps/webhooks/vendor/rubix/ml/src\Kernels\Distance\Gower.php", the first will be used.

- https://github.com/RubixML/Extras/blob/master/src/Kernels/Distance/Gower.php
- https://github.com/RubixML/ML/blob/master/src/Kernels/Distance/Gower.php

Same namespace: `Rubix\ML\Kernels\Distance\Gower`

PR: https://github.com/RubixML/ML/pull/242

**Comment by andrewdalpino** [comment]
I think we still need to remove Gower from the Extras package as we moved it over from Extras to the main package for version 2.2. Will do this as soon as I have time.

**Comment by andrey-helldar** [comment]
Thank you

**Comment by andrewdalpino** [comment]
Ok Gower was removed in Extras 2.0.1-beta so now it should be compatible with ML 2.2.0.

https://github.com/RubixML/Extras/releases/tag/2.0.1-beta

**Comment by andrey-helldar** [comment]
@andrewdalpino, thank you!
