### ISSUE TITLE
psr/log old version is limiting the project to be used on modern frameworks

### ISSUE THREAD

**Issue by allanmcarvalho** [andrewdalpino/Rubix-engine#278]
as mentioned on #199 
Isn't impossible to use this package with Laravel 9 and 10 because laravel requires monolog and monolog requires psr/log 2|3....
Can we easily upgrate the psr/log to 2 or 3?

**Comment by andrewdalpino** [comment]
Thank you so much @allanmcarvalho the fix has been released in ML 2.3.1

https://github.com/RubixML/ML/releases/tag/2.3.1

**Comment by allanmcarvalho** [comment]
You're welcome! Thanks for help all the community! This package is awesome!
