### ISSUE TITLE
Map method in Dataset doesn't exist

### ISSUE THREAD

**Issue by CViniciusSDias** [andrewdalpino/Rubix-engine#295]
According to [the documentation](https://docs.rubixml.com/2.0/datasets/api.html#mapping-and-filtering) a `map` method should exist in the `Dataset` type, but it doesn't. Either the documentation or the implementation is incorrect.

**Comment by Boorinio** [comment]
Fixed in https://github.com/RubixML/ML/pull/296

**Comment by andrewdalpino** [comment]
I went ahead and removed the old docs
