### ISSUE TITLE
Please remove this script

### ISSUE THREAD

**Issue by chrisjung-dev** [andrewdalpino/Rubix-engine#341]
Please remove this. There is a security attack going on from this domain. So your Docs are possibly containing malware!

https://github.com/RubixML/ML/blob/3b7032a4f21ae597662682254afca1bbdbbcf6d1/mkdocs.yml#L325

**Comment by chrisjung-dev** [comment]
@andrewdalpino

**Comment by andrewdalpino** [comment]
Thanks @campino2k
